services:
  - type: web
    name: email-scraper
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    # This is important - we need to install Chrome in the build phase
    buildFilter:
      paths:
        - package.json
      ignoredPaths:
        - node_modules
    # Set up the environment for Chrome
    plan: standard # Use at least standard tier for enough resources
    healthCheckPath: /ping
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 # Add some disk space